spring.application.name=StudentManagementSystem

spring.datasource.url=jdbc:postgresql://localhost:5432/student_management_system
spring.datasource.username=postgres
spring.datasource.password=anudnya

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# TRACE shows all 5 levels for your package
logging.level.root=INFO
logging.level.org.example.studentmanagementsystem=TRACE
logging.level.org.hibernate.SQL=DEBUG

logging.pattern.level=%5p [%X{requestId}]

logging.file.name=logs/student-app.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=14
logging.logback.rollingpolicy.total-size-cap=200MB